name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - '*'  # Run on all branches for pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Run only on branches on main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}

  build_other_branches:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'  # Run only on branches other than main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
